# *************************************************************************** #
#                                                                             #
#                                                        :::      ::::::::    #
#    integer.py                                        :+:      :+:    :+:    #
#                                                    +:+ +:+         +:+      #
#    By: nyramana <nyramana@student.42antananariv  +#+  +:+       +#+         #
#                                                +#+#+#+#+#+   +#+            #
#    Created: 2026/08/14 20:25:23 by nyramana         #+#    #+#              #
#    Updated: 2026/08/15 08:58:48 by nyramana        ###   ########.fr        #
#                                                                             #
# *************************************************************************** #

"""Module that contains th integer finite state machine."""

from enum import Enum, auto

from .base import StateMachine


class State(Enum):
    """Enum for the state machine."""

    START = auto()
    SIGN = auto()
    INTEGER = auto()
    END = auto()


class IntegerStateMachine(StateMachine):
    """
    State Machine for the integer type.

    This ensure the value generated by the llm is always right and follow the
    norme.
    """

    def __init__(self) -> None:
        """Everything start here."""
        self.state = State.START
        self.value = ""

    def can_accept(self, char: str) -> bool:
        """
        Check if the value can accept the charactere.

        Args:
            char (str): The charactere to verify the validity.
        Returns:
            bool: True if it's valid.
        """
        if self.state == State.START:
            return char.strip() in ("-", "+") or char.strip().isdigit()

        if self.state == State.SIGN:
            return char.isdigit()

        if self.state == State.INTEGER:
            return char.isdigit() or char == "."

        return False

    def transition(self, char: str) -> bool:
        """
        Change from one State to another.

        Args:
            char (str): The char to check.
        Returns:
            bool: True if it was successfull.
        """
        if not self.can_accept(char):
            return False

        self.value += char

        if self.state == State.START:
            self.state = State.SIGN if char == "-" else State.INTEGER

        elif self.state == State.SIGN:
            self.state = State.INTEGER

        return True

    def is_finished(self) -> bool:
        """
        Check if the value can be finished.

        Returns:
            bool: True if so.
        """
        return self.state == (State.INTEGER)
