# *************************************************************************** #
#                                                                             #
#                                                        :::      ::::::::    #
#    number.py                                         :+:      :+:    :+:    #
#                                                    +:+ +:+         +:+      #
#    By: nyramana <nyramana@student.42antananariv  +#+  +:+       +#+         #
#                                                +#+#+#+#+#+   +#+            #
#    Created: 2026/08/14 20:25:23 by nyramana         #+#    #+#              #
#    Updated: 2026/08/15 14:12:12 by nyramana        ###   ########.fr        #
#                                                                             #
# *************************************************************************** #

"""Module that contains the number state machine."""

from enum import Enum, auto

from .base import StateMachine


class State(Enum):
    """Enum for the state machine."""

    START = auto()
    SIGN = auto()
    INTEGER = auto()
    DOT = auto()
    DECIMAL = auto()
    END = auto()


class NumberStateMachine(StateMachine):
    """
    State Machine for the number type.

    This ensure the value generated by the llm is always right and follow the
    norme.
    """

    def __init__(self) -> None:
        """Everything start here."""
        self._state = State.START
        self.value = ""
        self._delimiters = {",", "}", "\n", '"'}

    def _next_state(self, state: State | None, char: str) -> State | None:
        if state == State.START:
            if char.isspace():
                return State.START
            if char in ("-", "+"):
                return State.SIGN
            if char.isdigit():
                return State.INTEGER
            return None

        if state == State.SIGN:
            if char.isdigit():
                return State.INTEGER
            return None

        if state == State.INTEGER:
            if char.isdigit():
                return State.INTEGER
            if char == ".":
                return State.DOT
            if char in self._delimiters:
                return State.END
            return None

        if state == State.DOT:
            if char.isdigit():
                return State.DECIMAL
            return None

        if state == State.DECIMAL:
            if char.isdigit():
                return State.DECIMAL
            if char in self._delimiters:
                return State.END
            return None

        if state == State.END:
            if char.isspace():
                return State.END
            return None

        return None

    def can_accept(self, char: str) -> bool:
        """
        Check if the value can accept the charactere.

        Args:
            char (str): The charactere to verify the validity.
        Returns:
            bool: True if it's valid.
        """
        state: State | None = self._state
        for current in char:
            state = self._next_state(state, current)
            if state is None:
                return False
        return True

    def transition(self, char: str) -> bool:
        """
        Change from one State to another.

        Args:
            char (Any): The char to check.
        Returns:
            bool: True if it was successfull.
        """
        for current in char:
            next_state = self._next_state(self._state, current)
            if next_state is None:
                return False

            if (
                next_state
                in (
                    State.SIGN,
                    State.INTEGER,
                    State.DOT,
                    State.DECIMAL,
                )
                and not current.isspace()
            ):
                self.value += current

            self._state = next_state
        return True

    def is_finished(self) -> bool:
        """
        Check if the value can be finished.

        Returns:
            bool: True if so.
        """
        return self._state in (State.INTEGER, State.DECIMAL, State.END)
