# *************************************************************************** #
#                                                                             #
#                                                        :::      ::::::::    #
#    string.py                                         :+:      :+:    :+:    #
#                                                    +:+ +:+         +:+      #
#    By: nyramana <nyramana@student.42antananariv  +#+  +:+       +#+         #
#                                                +#+#+#+#+#+   +#+            #
#    Created: 2026/08/15 00:33:18 by nyramana         #+#    #+#              #
#    Updated: 2026/08/15 09:00:37 by nyramana        ###   ########.fr        #
#                                                                             #
# *************************************************************************** #

"""Module that contains the string state machine."""

from enum import Enum, auto

from .base import StateMachine


class State(Enum):
    """Enum for the state machine."""

    START = auto()
    STRING = auto()
    ESCAPE = auto()
    END = auto()


class StringStateMachine(StateMachine):
    """
    State Machine for the string/other type.

    This ensure the value generated by the llm is always right and follow the
    norme.
    """

    def __init__(self) -> None:
        """Everything start here."""
        self.state = State.START
        self.value = ""

    def _next_state(self, state: State | None, char: str) -> State | None:
        if state == State.START:
            if char == '"':
                return State.STRING
            return None

        if state == State.STRING:
            if char == '"':
                return State.END

            if char == "\\":
                return State.ESCAPE

            return State.STRING

        if state == State.ESCAPE:
            if char in '"\\/bfnrt':
                return State.STRING

            return None

        if state == State.END:
            return None
        return None

    def can_accept(self, char: str) -> bool:
        """
        Check if the value can accept the charactere.

        Args:
            char (str): The charactere to verify the validity.
        Returns:
            bool: True if it's valid.
        """
        state: State | None = self.state

        for a in char:
            state = self._next_state(state, a)

            if state is None:
                return False
            if state == State.END:
                return True

        return True

    def transition(self, char: str) -> bool:
        """
        Change from one State to another.

        Args:
            char (Any): The char to check.
        Returns:
            bool: True if it was successfull.
        """
        for a in char:
            if self.state == State.START:
                self.state = State.STRING

            elif self.state == State.STRING:
                if a == '"':
                    self.state = State.END
                    return True
                elif a == "\\":
                    self.state = State.ESCAPE
                else:
                    self.value += a

            elif self.state == State.ESCAPE:
                self.value += a
                self.state = State.STRING
        return True

    def is_finished(self) -> bool:
        """
        Check if the value can be finished.

        Returns:
            bool: True if so.
        """
        return self.state == State.END
