[project]
name = "callmemaybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "flake8>=7.3.0",
    "flake8-docstrings>=1.7.0",
    "llm-sdk",
    "mypy>=2.3.0",
    "pydantic>=2.13.4",
    "readchar>=4.2.2",
    "rich>=15.0.0",
]

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true, editable = true }

[tool.mypy]
mypy_path = "llm_sdk"
